### ISSUE TITLE
cookbook doesn't install correctly using knife

### ISSUE THREAD

**Issue by ahmedjaved** [jgoulah/x11vnc-cookbook#1]
I have chef client installed version 10.18.1

When I install x11vnc cookbook using following command

``` bash
knife cookbook site install x11vnc
```

Here is the output I get 

``` bash
Installing x11vnc to /home/user/git/xubuntu-chef-solo/cookbooks
Checking out the master branch.
Creating pristine copy branch chef-vendor-x11vnc
Downloading x11vnc from the cookbooks site at version 0.0.2 to /home/user/git/xubuntu-chef-solo/cookbooks/x11vnc.tar.gz
Cookbook saved: /home/user/git/xubuntu-chef-solo/cookbooks/x11vnc.tar.gz
Removing pre-existing version.
Uncompressing x11vnc version 0.0.2.
ERROR: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of tar zxvf /home/user/git/xubuntu-chef-solo/cookbooks/x11vnc.tar.gz ----
STDOUT: 
STDERR: gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
---- End output of tar zxvf /home/user/git/xubuntu-chef-solo/cookbooks/x11vnc.tar.gz ----
Ran tar zxvf /home/user/git/xubuntu-chef-solo/cookbooks/x11vnc.tar.gz returned 2
```

It seems the chef client expects tarball however it ends up getting another format.

**Comment by jgoulah** [comment]
Ok, this is now fixed and working,  I think we may consider opening a bug with chef because they accept a bz2 format but it doesn't work with this command,  either they should not accept it, or could patch this command to work with multiple tar formats

# 

% knife cookbook site install x11vnc
Installing x11vnc to /home/jgoulah/dev/chef/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-x11vnc) exists, switching to it.
Downloading x11vnc from the cookbooks site at version 0.0.3 to /home/jgoulah/dev/chef/cookbooks/x11vnc.tar.gz
Cookbook saved: /home/jgoulah/dev/chef/cookbooks/x11vnc.tar.gz
Removing pre-existing version.
Uncompressing x11vnc version 0.0.3.
removing downloaded tarball
1 files updated, committing changes
Creating tag cookbook-site-imported-x11vnc-0.0.3
Checking out the master branch.
Updating dd7ed62..46dd923
Fast-forward
 cookbooks/x11vnc/README.md                         |    9 ++++++
 cookbooks/x11vnc/attributes/default.rb             |    3 ++
 cookbooks/x11vnc/metadata.rb                       |    6 ++++
 cookbooks/x11vnc/recipes/default.rb                |   28 ++++++++++++++++++++
 cookbooks/x11vnc/templates/default/x11vnc.conf.erb |    4 +++
 5 files changed, 50 insertions(+), 0 deletions(-)
 create mode 100644 cookbooks/x11vnc/README.md
 create mode 100644 cookbooks/x11vnc/attributes/default.rb
 create mode 100644 cookbooks/x11vnc/metadata.rb
 create mode 100644 cookbooks/x11vnc/recipes/default.rb
 create mode 100644 cookbooks/x11vnc/templates/default/x11vnc.conf.erb
Cookbook x11vnc version 0.0.3 successfully installed
